#version 430 core

#ifndef CUSTOM_DEFINES
#define WORK_GROUP_SIZE_X 1
#define WORK_GROUP_SIZE_Y 1
#define WORK_GROUP_SIZE_Z 1
#endif

layout (local_size_x = WORK_GROUP_SIZE_X, local_size_y = WORK_GROUP_SIZE_Y, local_size_z = WORK_GROUP_SIZE_Z) in;

layout(rgba32f, binding = 0) uniform image2D tex_output;

uniform float t;


void main() {
	vec4 value = vec4(0.0, 0.0, 0.0, 1.0);
	ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);
	float speed = 100;
	// the width of the texture
	float width = 1000;

	vec3 work_size = gl_NumWorkGroups * gl_WorkGroupSize;

	value.x = mod(float(texelCoord.x) + t * speed, width) / work_size.x;
	value.y = float(texelCoord.y) / work_size.y;
	imageStore(tex_output, texelCoord, value);
}